name: infra Terraform

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_VERSION: "1.12.2"
  TF_WORKING_DIR: EKS-Terraform

jobs:

  terraform:
    name: Terraform Validate, Plan & Apply
    runs-on: ubuntu-latest

    steps:

      # ============================================================
      # CHECKOUT REPOSITORY
      # ============================================================
      - name: Checkout Repository
        uses: actions/checkout@v4


      # ============================================================
      # AWS AUTHENTICATION
      # ============================================================
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity


      # ============================================================
      # TERRAFORM SETUP
      # ============================================================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Version
        run: |
          terraform version


      # ============================================================
      # TERRAFORM INIT
      # ============================================================
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init


      # ============================================================
      # TERRAFORM VALIDATE
      # ============================================================
      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform validate


      # ============================================================
      # TERRAFORM PLAN
      # ============================================================
      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan -out=tfplan


      # ============================================================
      # TERRAFORM APPLY
      # ============================================================
      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform apply -auto-approve tfplan


      # ============================================================
      # TERRAFORM OUTPUTS
      # ============================================================
      - name: Terraform Outputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform output
